### PR TITLE
Make Django2.0 compatible: use simple_tag, closes #69

### LINKED ISSUE #69: assignment_tag is removed in django-2.0
Quoting the [release docs](https://docs.djangoproject.com/en/2.0/releases/1.9/#deprecated-features-1-9):

> Django 1.4 added the assignment_tag helper to ease the creation of template tags that store results in a template variable. The simple_tag() helper has gained this same ability, making the assignment_tag obsolete. Tags that use assignment_tag should be updated to use simple_tag.

As this prevents a timely upgrade to Django 2.0 for me, I'd ask you to consider merging a PR and releasing a new version soon-ish.

### PR DESCRIPTION
**Pull request by rixx**
I saw the previous discussion on #65, and while I agree that dropping versions and other major changes should have to wait, I'm anxious to move to Django 2.0, and as long as this involves only a few corrected imports, I'd be really happy if you'd decide to merge this PR and make a patch release.

### CODE REVIEW

**Comment by rixx** [comment]
I don't quite see how the occurring pypy errors (occurring only with pypy between Django 1.5 and 1.7) can be this PR's fault, but if you point me in the right direction, I'll gladly tackle them.

**Comment by irconan** [comment]
@rixx Django 1.5-1.7 are all no longer supported, and were never supported by Django project with python version 3.5 (which this pypy3 is equivalent to). Personally, I think these test environments should just be removed.

**Comment by rixx** [comment]
Sounds plausible enough. @dfunckt, what do you think –could you merge this PR and provide a patch release?

**Comment by dfunckt** [comment]
d2a88315 adds Django 2.0 support. Thanks for the PR!

**Pull request closed without merging**
