### PR TITLE
WIP Use inspect.getfullargspec in python 3

### LINKED ISSUE #32: Support for PEP 484 annotations
Using function annotations in rules will cause this error (Python 3.5):

```
ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them

File "…/app/rules.py", line 3, in <module>
  from .predicates import (
File "…/app/predicates.py", line 13, in <module>
  def is_superuser(user: User):
File "…/django-rules/rules/predicates.py", line 246, in predicate
  return inner(fn)
File "…/django-rules/rules/predicates.py", line 241, in inner
  p = Predicate(fn, name, **options)
File "…/django-rules/rules/predicates.py", line 67, in __init__
  argspec = inspect.getargspec(fn)
File "/usr/lib64/python3.5/inspect.py", line 1045, in getargspec
  raise ValueError("Function has keyword-only arguments or annotations"
```

Ref: https://docs.python.org/3/library/inspect.html#inspect.getfullargspec

### PR DESCRIPTION
**Pull request by bulv1ne**
This fixes #32

### CODE REVIEW

**Comment by bulv1ne** [comment]
`wheel requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*' but the running Python is 3.3.6`

Maybe remove python 3.3 from travis-ci and tox.ini?

**Comment by dfunckt** [comment]
@bulv1ne thanks for the PR! I think that should fix the warning but not necessarily add support for functions with keyword-only arguments? For example, (I expect) this won't work:

```python
@rules.predicate
def kwargfunc(foo, *, bar=None):
  ...

rules.add_rule('foo', kwargfunc)
rules.test_rule('foo', 'a', 'b')
```

What I would expect from `rules` in this case is to invoke `kwargfunc` as `kwargfunc('a', bar='b')`.

**Comment by bulv1ne** [comment]
Now I understand the issue more clearly. Will see if I can solve this :+1:

**Comment by bulv1ne** [comment]
In issue #32, in the error message mentions that if fails on an annotation, not a kwargfunc as you mentioned. Does rules want support for kwargfuncs like the one you wrote? I don't see a use case to be honest where the predicate function has only a keyword argument.

**Comment by dfunckt** [comment]
OK, I think I see now. First of all, this PR actually fixes two issues -- #32 and #57. And I think what I remember as not being straightforward is I tried to use `inspect.signature` (as suggested by the error message shown in #57) which is a completely different API, and I probably somehow missed `getfullargspec` existed.

> Does rules want support for kwargfuncs like the one you wrote? I don't see a use case to be honest where the predicate function has only a keyword argument.

You're right, I think not -- rules only really works with positional arguments, please forget my sentence about what I'd expect rules to do. However, we still need to (now manually) forbid unsupported function signatures though. Consider this example, where the keyword-only argument doesn't have a default value:

```
@rules.predicate
def kwargfunc(foo, *, bar):
  ...
```

Up until now, the above would throw an error immediately upon importing the module the predicate is in. With this PR, it will not throw an error on import (the predicate will indeed be created), but when `test_rule` is called because keyword-only arguments can only be called, well, by keyword and rules is only passing positional arguments to the predicate.

So what I suggest is to inspect the function and if it has keyword-only arguments without a default value, raise a ValueError alerting about the fact that the function is incompatible. What do you think?

We'll also need to have tests for all this :) Bonus points if coverage is kept to 100%!

**Comment by dfunckt** [comment]
And let's ignore the Travis failure on Python 3.3 for now -- I'll remove support for it in a separate commit.

**Comment by bulv1ne** [comment]
I still think it's a rare case but a more possible one though.
I think I could manage to let it raise TypeError (as you already are using) but I don't know how to write the test so Python 2 wouldn't complain. Right now I receive:

```
def kwargfunc(foo, *, bar):
                    ^
SyntaxError: invalid syntax
```

Any idea how to write the test in a clear way (without using exec)? The following function is a valid one and should not raise an exception.

```
@rules.predicate
def kwargfunc(*foo):
    pass
```

**Comment by dfunckt** [comment]
You can try adding the test cases to a separate file and the following in `test_predicates.py`:

```
try:
  from inspect import getfullargspec
except ImportError:
  pass
else:
  from _test_predicates_kwonly import *
```

Just make sure the new filename doesn't start with `test_` or it'll be picked up automatically.

**Comment by bulv1ne** [comment]
It looks like a hack to be honest, but I don't know another way. Your solution will be easy to migrate once Python 2 support is dropped.

**Comment by bulv1ne** [comment]
I marked this as WIP (work in progress) until I'm done. For now it looks like it's working but calling getargspec (Python 2 one) on a partial doesn't work, while getfullargspec works perfectly in Python 3

**Comment by bulv1ne** [comment]
@dfunckt any updates on this PR? 🙂

**Comment by dfunckt** [comment]
@bulv1ne this PR is in 211fcd4f and ships with rules-1.4. Thanks!

**Pull request closed without merging**
