### PR TITLE
Update supported versions and switch to GitHub Actions

### PR DESCRIPTION
**Pull request by zerolab**
- Drops Python < 3.6
- Django < 2.2

To-Do

- [x] Switch to GitHub Actions
- [x] add tests against Django mainline

### CODE REVIEW

**Comment by zerolab** [comment]
@dfunckt I think this is pretty much there. Note that since this is my first contribution to this repository, you have to manually allow the CI to run

**Comment by dfunckt** [comment]
@zerolab thanks for the PR! Not sure why status isn't synchronised but the builds do run fine over at Travis: https://travis-ci.org/github/dfunckt/django-rules

**Comment by zerolab** [comment]
Since we're switching to GitHub Actions, https://github.blog/2021-04-22-github-actions-update-helping-maintainers-combat-bad-actors/ comes into play

Done with with. Will submit as separate pre-commit with linting (black, flake8, isort), if you'd like to

**Comment by dfunckt** [comment]
I unfortunately don't get a button to approve like the blog post shows, but have tested your changes in #140 and seem to work after a couple of modifications to ci.yml -- if you could integrate my changes to this PR I will happily merge.

**Comment by zerolab** [comment]
Thank you. Incorporated the ci.yml changes from #140 in ddb7d88. 

Interestingly, I had the coveralls GitHub action initially, then got sidetracked by https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#github-actions-support.

**Comment by dfunckt** [comment]
Thank you @zerolab !

**Pull request merged**
