### PR TITLE
Do not call get_object in BaseCreateView

### PR DESCRIPTION
**Pull request by dyve**
This is a fix for issue #85.

### CODE REVIEW

**Comment by dyve** [comment]
@dfunckt It's not the prettiest solution (might even be a Django bug), but this solves it for now.

**Comment by lwm** [comment]
:100:

**Comment by bulv1ne** [comment]
Another solution would be to check if `self.kwargs` is empty. Though I don't see when checking inheritance from BaseCreateView would be wrong.

**Comment by dyve** [comment]
@dfunckt Could you respond to this PR and tell us if there's any chance of a release with this fix?

**Comment by dfunckt** [comment]
@dyve do you want this backported to 1.x as well?

**Comment by dyve** [comment]
We use 2+ o all our projects, so no need on our behalf.

**Pull request merged**
